channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - r-base =3.6.1
  - r-shiny =1.4.0.2
  - r-shinydashboard =0.7.1
  - r-shinythemes =1.1.2
  - r-dt =0.12
  - r-formattable =0.2.0.1
  - r-tidyverse =1.3.0
  - r-ggplot2 =3.3.0
  - r-data.table =1.12.8
  - r-dplyr =0.8.5
  - r-stringr =1.4.0
  - r-reshape2 =1.4.3
  - r-rsqlite =2.2.0
  - r-splitstackshape =1.4.8
